default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['YOUR_DATABASE_USERNAME'] %>
  password: <%= ENV['YOUR_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: test_rails_api_development

test:
  <<: *default
  database: test_rails_api_test

production:
  <<: *default
  database: test_rails_api_production
  username: test_rails_api
  password: <%= ENV['TEST_RAILS_API_DATABASE_PASSWORD'] %>
